kind: Service
apiVersion: v1
metadata:
  namespace: dock
  name: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
---
kind: Endpoints
apiVersion: v1
metadata:
  namespace: dock
  name: database
subsets:
  - addresses:
      - ip: 172.16.1.4 # IP do banco
    ports:
      - port: 5432
